services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_LISTENER_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - academic-audit-system-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - academic-audit-system-network
    volumes:
      - ./app-data/kafka-data:/var/lib/kafka/data

  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongo
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=root
    networks:
      - academic-audit-system-network
    ports:
      - "27017:27017"
    volumes:
      - ./app-data/mongo-data:/data/db
      #- mongo-volume:/data/db

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    networks:
      - academic-audit-system-network

  postgres:
    image: postgres:13
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: academic_audit_system_db
    networks:
      - academic-audit-system-network
    ports:
      - "5432:5432"
    volumes:
      - ./app-data/postgres-data:/var/lib/postgresql/data

volumes:
  mongo-volume:

#  gateway:
#    image: aas-gateway:latest
#    container_name: gateway
#    networks:
#      - academic-audit-system-network
#    ports:
#      - "8080:8080"

networks:
  academic-audit-system-network:
    driver: bridge
