# Generated by Django 3.2.16 on 2025-04-23 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalyzeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_status', models.CharField(max_length=50)),
                ('user_id', models.BigIntegerField()),
                ('document_id', models.CharField(max_length=255)),
                ('report_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document_analyze_request',
            },
        ),
    ]
